# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

interp_rcpp <- function(a, b, n) {
    .Call('_gridfit_interp_rcpp', PACKAGE = 'gridfit', a, b, n)
}

trilinear_rcpp <- function(x, y, z, values, points) {
    .Call('_gridfit_trilinear_rcpp', PACKAGE = 'gridfit', x, y, z, values, points)
}

